export { default as Home } from './Home/Home'
export { default as Landing } from './Landing/Landing'
export { default as Register } from './Register/Register'
export { default as Login } from './Login/Login'
export { default as Error } from './Error/Error'
export { default as SinglePageError } from './SinglePageError/SinglePageError'
